### ISSUE TITLE
node-expat invalid ELF header

### ISSUE THREAD

**Issue by newsroomdev** [hipchat/hubot-hipchat#127]
trying to deploy hubot-hipchat from an ec2 instance, but it keeps saying i've got an invalid ELF header.

i'm running `npm install` from the server, not my local machine before pushing it to the server. additionally, this is a new server so there are no other conflicting versions of nodejs.

anyone else have a similar issue?

**Comment by CarLoOSX** [comment]
rbergman was OK , it works for me ! Thanks

**Comment by dubcdr** [comment]
https://medium.com/@devontem/solved-invalid-elf-header-with-docker-and-bcrypt-444426d63605

**Comment by dubcdr** [comment]
@powdahound i got you

https://medium.com/@devontem/solved-invalid-elf-header-with-docker-and-bcrypt-444426d63605

**Comment by depperm** [comment]
As mentioned above `npm rebuild` worked for me
