### ISSUE TITLE
Hubot Unable to Connect

### ISSUE THREAD

**Issue by aranw** [hipchat/hubot-hipchat#144]
Am trying to add Hubot to Hipchat, I've created the user added the login details and host. But in the logs the only thing am getting is...

```
[Thu Sep 19 2013 05:21:21 GMT-0400 (EDT)] INFO Connecting HipChat adapter...
[Thu Sep 19 2013 05:21:23 GMT-0400 (EDT)] DEBUG Loading adapter hipchat
[Thu Sep 19 2013 05:21:23 GMT-0400 (EDT)] DEBUG HipChat adapter options: {"jid":"66792_466246@chat.hipchat.com","password":"","token":null,"rooms":"All","host":"chat.hipchat.com","autojoin":true}
```

I can't figure out why it can't connect, the three lines above just repeat continuously.

I've not followed the instructions exactly in the README.md as am trying to run this on my own VM rather than herkou.  

Am also trying to keep the bot running using Supervisord.

**Comment by rgalindo33** [comment]
hi @aranw , what did you do  to get it working?

**Comment by aranw** [comment]
Hey @rgalindo33, sorry I really can't remember what I did to fix this issue, but from my comment am guessing I might of missed the port configuration maybe?
