### ISSUE TITLE
latest node-xmpp causing error when running locally on osx

### ISSUE THREAD

**Issue by benlong** [hipchat/hubot-hipchat#164]
I'm getting an error (below) with the following configurations:
OSX, node-0.9 (or greater), node-xmpp-0.12.0

The error does not happen with the following configurations:
OSX, node-0.8.26 (or lower), node-xmpp-0.12.0
OSX, node-0.10.26 (or lower), node-xmpp-0.3.2
(basically, new node/old xmpp, or old node/new xmpp)

The error started happening here:
https://github.com/hipchat/hubot-hipchat/commit/73f959aa68df7afeafe0b028b68cf47723dfe71a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

How to reproduce: a fresh install using latest node..
```
./bin/hubot --adapter hipchat
```

The error
```
dyld: lazy symbol binding failed: Symbol not found: _usprep_openByType_49
  Referenced from: /sdev/hubot/snapbot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/build/Release/node_stringprep.node
  Expected in: dynamic lookup
 
dyld: Symbol not found: _usprep_openByType_49
  Referenced from: /sdev/hubot/snapbot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/build/Release/node_stringprep.node
  Expected in: dynamic lookup
 
Trace/BPT trap: 5
```

**Comment by rbergman** [comment]
Several updates have been made that should fix this so long as you are using Node 0.10.x or later (preferably 0.12.x these days).
