### ISSUE TITLE
Hubot's default configuration is to join every available room

### ISSUE THREAD

**Issue by requalix** [hipchat/hubot-hipchat#165]
Hubot is configured to join every available room by default. This behaviour can be problematic if there are many rooms (e.g. automatic banning, clients crashing, etc). For large servers it seems unlikely that a bot would be wanted in all rooms, by default.

Perhaps a more suitable default behaviour is joining no rooms at all.

**Comment by rbergman** [comment]
Agree with rahulsom's argument.
