### ISSUE TITLE
Send message disconnecting hubot

### ISSUE THREAD

**Issue by pareeohnos** [hipchat/hubot-hipchat#166]
I'm creating a small script which fetches a console log from an API, and returns the last 20 lines to the user. Everything is working except for the response part.

It seems that trying to send one of the following lines, causes something to go completely wrong

    [31m>> [39m
    [31mFatal error: protractor exited with code: 8[39m

I'm not sure what's happening as there aren't any actual errors output, and hubot stays running, however it disconnects from hip chat and the message is never sent. If I try outputting the content below those lines, it works as expected.

My script is something like this

    response = body
    msg.send "/code #{response}"

I am doing a few more things with the response but nothing much, and I've tried outputting the body itself and that cause the same issue so I know it's not my processing. 

When I run the script with the standard shell adapter, hubot responds as expected, so I'm assuming the issue lies with the hip chat adapter

I've also tried escaping all characters I can think of such as single/double quotes, square brackets, angle brackets etc... and it hasn't helped so I'm pretty stumped

**Comment by rbergman** [comment]
#206 has been merged.
