### ISSUE TITLE
Hubot not listening in HipChat

### ISSUE THREAD

**Issue by andrewrrose** [hipchat/hubot-hipchat#167]
Followed the instructions (I think).

./hubot.sh
[Fri Mar 07 2014 13:46:25 GMT-0800 (PST)] DEBUG Loading adapter hipchat
[Fri Mar 07 2014 13:46:26 GMT-0800 (PST)] DEBUG HipChat adapter options: {"jid":"7542_710420@chat.hipchat.com","password":"<0000000000000>","token":"<000000000000000000>","rooms":"7542_nothing@conf.hipchat.com","host":null,"autojoin":true}
[Fri Mar 07 2014 13:46:26 GMT-0800 (PST)] INFO Connecting HipChat adapter...
[Fri Mar 07 2014 13:46:26 GMT-0800 (PST)] DEBUG  OUT > <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">NzU0Ml83MTA0MjBAY2hhdC5oaXBjaGF0LmNvbQA3NTQyXzcxMDQyMABIdUJvdFNlZW1zTGVnMXQ=</auth>
[Fri Mar 07 2014 13:46:26 GMT-0800 (PST)] DEBUG  OUT > <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>hubot-hipchat</resource></bind>
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] DEBUG  OUT > <session xmlns="urn:ietf:params:xml:ns:xmpp-session"/>
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] DEBUG  OUT > <presence type="available"><show>chat</show><c xmlns="http://jabber.org/protocol/caps" node="http://hipchat.com/client/bot" ver="hubot-hipchat:2.6.4"/></presence>
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] DEBUG  OUT > <iq type="get" id="1"><vCard xmlns="vcard-temp"/></iq>
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] INFO Connected to hipchat.com as @HuBot
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] DEBUG Loading scripts from /Users/arose/hubot/scripts
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] DEBUG Loading scripts from /Users/arose/hubot/src/scripts
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] DEBUG  OUT > <iq type="get" id="2"><query xmlns="jabber:iq:roster"/></iq>
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] DEBUG Loading hubot-scripts from /Users/arose/hubot/node_modules/hubot-scripts/src/scripts
[Fri Mar 07 2014 13:46:27 GMT-0800 (PST)] DEBUG Loading external-scripts from npm packages
[Fri Mar 07 2014 13:46:28 GMT-0800 (PST)] INFO Joining 7542_nothing@conf.hipchat.com
[Fri Mar 07 2014 13:46:28 GMT-0800 (PST)] DEBUG  OUT > <presence to="7542_nothing@conf.hipchat.com/Hugh Bot"><x xmlns="http://jabber.org/protocol/muc"/><history xmlns="http://jabber.org/protocol/muc" maxstanzas="0"/></presence>
[Fri Mar 07 2014 13:46:57 GMT-0800 (PST)] DEBUG  OUT > <r/>
[Fri Mar 07 2014 13:47:27 GMT-0800 (PST)] DEBUG  OUT > <r/>
[Fri Mar 07 2014 13:47:57 GMT-0800 (PST)] DEBUG  OUT > <r/>

**Comment by brockoffdev** [comment]
@andrewrrose did you solve this issue by any chance?  I am seeing the exact same error.
