### ISSUE TITLE
Hubot Disconnects, but is still running

### ISSUE THREAD

**Issue by buddylindsey** [hipchat/hubot-hipchat#173]
Not sure where/how to start solving this issue, but our hubot will stay working fine in our room for a while, 15 to 20 minutes, then disconnect. No error or anything. We have the bot running with an upstart script and the process is still going. Also been running the hubot log level at debug and it is still outputting its `>` consistently so it doesn't error. Is there a good way to start figuring out why it is disconnecting?

**Comment by facundofarias** [comment]
We are still facing this issue, not sure why.
What we've detected is that on HipChat seems to be disconnected, but if we put a command, it is correctly executed. It only happens with the latest HipChat (3.1.6).
