### ISSUE TITLE
Should reply_to and room be saved on user object?

### ISSUE THREAD

**Issue by johnrengelman** [hipchat/hubot-hipchat#175]
Running into an issue where when I try to send a direct message to a User it always ends up in the last room that they wrote something from.

Looks like the `handleMessage` function in `hipchat.coffee` retrieves a User from Hubot's brain and then sets the `reply_to` and `room` attributes on it before passing it along to the `receive` function for further processing.

However, it seems these values then get stored on the User object and subsequent look ups of the User return that data (I think due to Hubot's autosave feature).

Is this the intended behavior?

I can get around the problem now, but specifically sending the message to `user.jid` but that's not portable when the HipChat plugin isn't being used.

**Comment by rbergman** [comment]
Merged and published.
