### ISSUE TITLE
Update procedures for Hubot-Hipchat

### ISSUE THREAD

**Issue by darksheer** [hipchat/hubot-hipchat#179]
What are the procedures for updating an older install of hubot-hipchat.  I'd be more than willing to help write a how-to guide but need some pointers in the right direction.

**Comment by rbergman** [comment]
This is a good question, but I don't have a good answer.  If someone has any advice, please feel free to write it up and PR the README.  In the meantime, I'm closing this since formal upgrade support is unlikely.
