### ISSUE TITLE
On the quick start, one of the dependency fails to link it

### ISSUE THREAD

**Issue by facundofarias** [hipchat/hubot-hipchat#180]
When following the instructions and installing dependencies, icu4c is installed correctly, but when I run:

`% brew link icu4c`

I got this message: 

**Warning: icu4c is keg-only and must be linked with --force
Note that doing so can interfere with building software.**

By adding the --force option, I got this message: 

**Linking /usr/local/Cellar/icu4c/52.1...
Error: Could not symlink include/layout
/usr/local/include is not writable.**

**Comment by rbergman** [comment]
Removed icu4c dependency from the docs, as it should no longer be required.
