### ISSUE TITLE
multiple message processing after reconnect

### ISSUE THREAD

**Issue by stesie** [hipchat/hubot-hipchat#186]
Hi,

I just recently started using hubot-hipchat adapter (after using the irc adapter).  With the hipchat adapter hubot processes messages multiple times, one extra time per reconnect.

Haven't looked into it but sounds like message handlers are reinstalled on reconnect even so that shouldn't be done ...

cheers

  ~stesie

**Comment by rbergman** [comment]
Fix has been merged and published.
