### ISSUE TITLE
Add a "Deploy to heroku" button!

### ISSUE THREAD

**Issue by loopj** [hipchat/hubot-hipchat#190]
https://blog.heroku.com/archives/2014/8/7/heroku-button

**Comment by rbergman** [comment]
OMG, I did a thing.

**Comment by loopj** [comment]
Nice!

**Comment by aseemk** [comment]
Agreed, nice!

We've moved from HipChat to Slack, so unfortunately can't use/test your work, but thanks nonetheless!

**Comment by cycomachead** [comment]
:+1: 

I don't really need a second chatbot, but this is nice!
