### ISSUE TITLE
XMPP authentication failure

### ISSUE THREAD

**Issue by jasonallen** [hipchat/hubot-hipchat#193]
Followed the steps to install hubot-hipchat on heroku, but it won't connect to hipchat. I can run & connect with the same code locally (OSX), but no dice on heroku. Turned on debug, and I see this:

```
DEBUG HipChat adapter options: {"jid”:”<myjid>,”password”:”<“my_pw>,”token":null,"rooms”:”<default_rooms>,”rooms_blacklist":"","host":null,"autojoin":true,"xmppDomain":null,"reconnect":true}
DEBUG  OUT > <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN”>_very_long_token_</auth>
ERROR null, null, 'XMPP authentication failure'
```

**Comment by rbergman** [comment]
Try the latest merged and published version of the adapter, and/or use the new deploy-to-heroku button.
