### ISSUE TITLE
Hubot connecting but not entering rooms or answering to commands

### ISSUE THREAD

**Issue by gheylen** [hipchat/hubot-hipchat#204]
Today, when I came in, I noticed that our bot appeared online in the lobby, but not appearing online in any of the rooms it should be in. Also, the Group Admin pages of HipChat show that the user which the bot uses to connect to HipChat hasn't been connected since yesterday.

This is rather strange. It is connected, because we get a green circle in the lobby, but it doesn't show on the admin pages of HipChat. Also, it doesn't answer.

Another strange thing is that it does respond when you spam "help" during its startup. After that it just goes silent again. How can it respond on HipChat and not have itself logged as "logged in" @ hipchat admin pages? oO

Anyone else having problems? I haven't touched the bot, its config, or its environment for a while. Suddenly it stopped working. So naturally I thought about changes on the HipChat side, or the Heroku side. Which means other people should also have problems?

Thanks for feedback.

**Comment by pusherman** [comment]
If you are using a self hosted version of hipchat be sure to 

$ export HUBOT_HIPCHAT_XMPP_DOMAIN=btf.hipchat.com

**Comment by rbergman** [comment]
OP's issue appeared to be a dup of #203.  Any other issues discussed here that are still a problem after adopting the latest npm publish should create a new issue.
