### ISSUE TITLE
Hubot does not show as online with HipChat

### ISSUE THREAD

**Issue by aaronmaxlevy** [hipchat/hubot-hipchat#220]
A recent change in what I presume is HipChat's XMPP API appears to cause current hubot-hipchat bots to appear as offline, even when they are online. Note that bots will still respond and send messages, however they still appear to be offline.

**Comment by diwu1989** [comment]
I'm seeing the same problem

**Comment by enigmait** [comment]
I have observed this too.

**Comment by tedder** [comment]
saw this too. it appears to be with a recent client- coworkers on older clients (especially Linux) see hubot as 'green'.

Contacted Hipchat today and they said "At the moment we are not aware of any issues in Hubot from our side, so it seems to be a client-related issue", then told me how to clear the cache.

**Comment by aaronmaxlevy** [comment]
Yeah I am not so sure this is a client issue. This started happening yesterday and I was on the same version of the client before and after this happened. It is possible that I just didn't notice until later, but I am hesitant to assume that it is a bug with the client.

**Comment by aaronmaxlevy** [comment]
Yeah I am not so sure this is a client issue. This started happening yesterday and I was on the same version of the client before and after this happened. It is possible that I just didn't notice until later, but I am hesitant to assume that it is a bug with the client.

**Comment by aaronmaxlevy** [comment]
That said, I just tried the web client and my Hubot shows as being online, so I'm pretty baffled. Maybe this is a client issue, but what is the scope of this I wonder. Are all XMPP HipChat users affected, and not just Hubot?

**Comment by tedder** [comment]
right, looks 'green' on the web client.

**Comment by aaronmaxlevy** [comment]
@tedder I would follow up with Hipchat and point them to this Github issue so that they know it is not an isolated incident. As far as I know, all HipChat Hubot users (at least using the latest client) are seeing this. If you search on Twitter you can find one or two more people talking about this issue

**Comment by kajisaap** [comment]
:+1: @aaronmaxlevy . I am on the same boat.

**Comment by kajisaap** [comment]
Little update. If i change the status of Hubot from HipChat web client, Hubot appears online briefly in HipChat Mac client and goes back to unavailable.

**Comment by d4v3y0rk** [comment]
I am also seeing the exact same thing. OSX client for HipChat shows "unavailable" for hubot and web client shows "Available".

**Comment by tedder** [comment]
Hipchat confirmed: "We've tested this further in a local environment and it's confirmed as a bug. We don't have an ETA of when this is going to be fixed, but we strongly recommend you to always keep your HipChat client up to date."

**Comment by danieljimenez** [comment]
For what it's worth, seeing the same thing here. Thanks for reporting.

**Comment by brandonhilkert** [comment]
Same here. Green in web client, unavailable in OSX client.

**Comment by jodyferry** [comment]
Same here.

**Comment by warwickp** [comment]
Same here.

**Comment by rbergman** [comment]
This is a confirmed Mac client bug.

**Comment by ccarey-netflix** [comment]
I got the latest Mac client update to v3.2 and the problem persists. HipChat Hubot shows as Unavailable still.

**Comment by facundofarias** [comment]
Yeah. The same it's happening to me.

**Comment by alhafoudh** [comment]
+1

**Comment by mshowaib** [comment]
+1

**Comment by esigler** [comment]
FYI, internally this is being tracked as an issue with the Hipchat Mac OSX client, HC-7228.

**Comment by jnolen** [comment]
We deployed a server-side change today that may alleviate (though not completely fix) this problem. If you were experiencing this behavior, I'd appreciate you giving it a try and letting me know if the change has helped.

**Comment by tedder** [comment]
@jnolen what do we need to do to test? log out of our OSX client, restart hubot, etc?

**Comment by jnolen** [comment]
Yes, I would suggest restarting your client and restarting HuBot to make sure you've got fresh sessions for each.

**Comment by d4v3y0rk** [comment]
I did both and no luck.

**Comment by danieljimenez** [comment]
Ditto.

**Comment by jnolen** [comment]
Alright, thanks everyone. We'll dive back in.

**Comment by lukaszraczylo** [comment]
@jnolen issue still present, unfortunately.

**Comment by naxIO** [comment]
yeah, +1 here

**Comment by tdensmore** [comment]
yes. I still see the issue, too. I know this is a minor bug, but would love to see it fixed...

**Comment by seybsen** [comment]
Same here. Checking for updates daily. :-)

**Comment by chriscareycode** [comment]
Why is this issue marked as closed when the bug still exists?

**Comment by rbergman** [comment]
Because it's not a hubot-hipchat bug.

On Sunday, March 22, 2015, chriscareycode <notifications@github.com> wrote:

> Why is this issue marked as closed when the bug still exists?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hipchat/hubot-hipchat/issues/220#issuecomment-84667120>
> .
>


-- 
By the power of Greyskull

**Comment by y2chaits** [comment]
@esigler Any way to track the status of HC-7228 ? 

> FYI, internally this is being tracked as an issue with the Hipchat Mac OSX client, HC-7228

**Comment by ckelner** [comment]
Any update on this?

**Comment by atljeremy** [comment]
Having the same issue here. +1

**Comment by rbergman** [comment]
We have a fix for this internally.  I don't have a release date, but it should be Coming Soon™.

**Comment by danieljimenez** [comment]
Thanks for the update @rbergman.

**Comment by asatkowski** [comment]
Thanks @rbergman.

**Comment by chriscareycode** [comment]
HipChat for Mac 3.3 that came out today fixes the issue.

**Comment by cycomachead** [comment]
:+1: 

Thanks! :)
