### ISSUE TITLE
Hubot Connects to Hipchat, But Does Not Receive Incoming Messages

### ISSUE THREAD

**Issue by brockoffdev** [hipchat/hubot-hipchat#221]
Hey Everybody-

So I am super confused, and am wondering if anyone else has experienced this issue.

Basically, the Hubot connects without a problem to our hipchat service, and our rooms, with the user being shown as active.  However, Hubot is not receiving and/or retrieving any of the messages we are sending via group and/or 1:1 chats.  

Here's a copy of my packer.json:

```
{
  "name": "hubot",
  "version": "2.7.5",
  "author": "hubot",
  "keywords": [
    "github",
    "hubot",
    "campfire",
    "bot"
  ],
  "description": "A simple helpful robot for your Company",
  "licenses": [
    {
      "type": "MIT",
      "url": "https://raw.github.com/github/hubot/master/LICENSE"
    }
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/github/hubot.git"
  },
  "dependencies": {
    "cheerio": "^0.18.0",
    "coffee-script": "1.6.3",
    "date-utils": "^1.2.16",
    "express": "3.18.1",
    "githubot": "^1.0.0-beta2",
    "htmlparser": "^1.7.7",
    "hubot-google-images": "^0.1.2",
    "hubot-google-translate": "^0.1.0",
    "hubot-hipchat": "^2.7.5",
    "hubot-http-status": "^0.2.0",
    "hubot-karma-classic": "^1.0.1",
    "hubot-pager-me": "^2.0.2",
    "hubot-rules": "^0.1.0",
    "hubot-scripts": "^2.5.16",
    "hubot-standup-alarm": "0.0.3",
    "icinga-hubot-script": "^0.1.23",
    "log": "1.4.0",
    "moment": "^2.9.0",
    "optparse": "^1.0.4",
    "readline-history": "~1.2.0",
    "request": "^2.51.0",
    "scoped-http-client": "0.10.0",
    "scraper": "0.0.9",
    "soupselect": "^0.2.0",
    "underscore": "^1.7.0",
    "underscore.string": "^2.4.0",
    "wolfram": "^0.3.0",
    "xml2js": "^0.4.4"
  },
  "engines": {
    "node": ">= 0.8.x",
    "npm": ">= 1.1.x"
  },
  "main": "./index",
  "bin": {
    "hubot": "./bin/hubot"
  }
}
```

And as I said, it connects no problem:

```[Fri Jan 09 2015 20:12:51 GMT-0500 (EST)] INFO Connected to hipchat.com as ___```

So it does seem to be related to a Hubot error, but I'm not seeing any kind of error in Debug. Thoughts?

**Comment by brockoffdev** [comment]
As an update to this question...

Lita's HIpchat plugin does not appear to be having any issues currently.  I am definitely looking to use Hubot though, so I am hoping to work with the community here to figure out what may be driving the Hipchat Hubot to not be hearing the platform correctly.  Thanks all!

**Comment by brockoffdev** [comment]
ANOTHER update. :) 

hubot-hipchat@2.5.1-5 appears to be the last version, at least on my box, that is able to properly listen for incoming messages...Every version after that I have tried has not.  Very strange.

**Comment by rbergman** [comment]
Several updates have been merged and published.  Please retry with the latest adapter and node.  Feel-free to re-open with any new information fi the problem persists.
