### ISSUE TITLE
State of support for hubot-hipchat?

### ISSUE THREAD

**Issue by esigler** [hipchat/hubot-hipchat#223]
Howdy!  Apologies for what may seem like an odd question, but I contacted Hipchat Support (regarding #220) and along with the answer to the presence issue (Mac client bug), they indicated this adapter is no longer supported:

(conversation edited for clarity, I'm happy to provide more details / contact info if needed)

> support@hipchat> Please also notice that Hubot is no longer supported by Atlassian as it has been replaced by the "GitHub for HipChat" plugin, so you may want to install this plugin (if it fits for what you need) to verify if fits for your needs. You can install this plugin at hipchat.com/admin/addons.

> myself>  I’d like to understand the comment "Hubot is no longer supported by Atlassian” in more detail.  Specifically, are you saying the hubot-hipchat adapter is no longer supported, the XMPP transport being used by the hubot-hipchat adapter is no longer supported, the functionality for Github notifications from hubot is no longer supported, or something else?

> support@hipchat> The Hubot-HipChat adapter is no longer supported, as currently we are working with the "GitHub for HipChat" adapter instead.

I suspect this might be just a case of "copy-and-paste" support with a stock answer for all things hubot - but can someone here comment on the state of support for this adapter?

**Comment by tcrusson** [comment]
Hi there, 
I'm a product manager in the HipChat team. This project was implemented by Bob as a side project and was never an officially supported feature, however we're currently looking at how it's used and we definitely see a lot of potential with bots in HipChat - along side vanilla integrations. In any case it still works, and we're not planning on retiring it at this stage. We also definitely welcome contributions! I'll have a chat with our support team to make sure we're on the same page.

**Comment by Jamesford** [comment]
@tcrusson glad to hear that you aren't planning retiring this adapter. My team and I had a few issues with it, however, while working on [ChatO.ps](http://chato.ps/). All is good now though, and you can easily fire up a bot that will connect to HipChat.

Sorry if this is off-topic, but I thought I'd grab your attention while you are here. I've submitted a pull request for the smaller issue we had https://github.com/hipchat/hubot-hipchat/pull/224, since we're managing a lot of hubots we don't keep the same file structure as normal and this little deviation from other adapters caught us out.

Additionally we've come across the same issue that @brockoffdev is having here https://github.com/hipchat/hubot-hipchat/issues/221

**Comment by justinwalsh** [comment]
+1

We are still having issue getting our hubot to respond to messages in rooms. From the debug info it looks like the bot is seeing the command and issuing a response but the message never arrives in hipchat.

**Comment by csanner** [comment]
so the adapter works mostly fine for us - there were definitely some config gotchas initially and I'd be happy to assist anyone who needs it.
in the meantime is there any chance of marking the last few bugfixes as a "release" so we can pull them in when the bot starts without having to fork it locally?

**Comment by davelesser** [comment]
@tcrusson, I don't mean to pile on here, but given https://github.com/hipchat/hubot-hipchat/pull/230, the current state `hubot-hipchat` is no longer:
> it still works

Any chance someone at Atlassian could look at the PR?

**Comment by rbergman** [comment]
Several PRs have been merged.
