### ISSUE TITLE
robot.respond and msg.reply do not work in a Room

### ISSUE THREAD

**Issue by oncletom** [hipchat/hubot-hipchat#228]
Hello,

for some reason, there is an issue with (private?) rooms when I mention a bot/reply to a user:

```js
// callback is called when a message (1 to 1 or public) contains 'http'
robot.hear(/http/i, function(msg){ 
  // will be called in 1 to 1, not in public
  msg.reply('Sure');
});

// workaround
robot.hear(new RegExp(robot.name + '.+http', 'i'), function(msg){ ... });

// callback is not called when 
robot.respond(/http/i, function(msg){ ... });
```

It's a bit weird and debugging coffeescript is not my cup of tea :-(

**Comment by rbergman** [comment]
Can you retry using the latest hubot/hubot-hipchat?  I can't reproduce this on the latest build, but maybe I'm missing something in your case?  Please re-open with more information if you continue to have the issue after trying the latest.

**Comment by oncletom** [comment]
@rbergman hello – thanks for your support :-) I tried again and got it does not work either.

"It does not work":

- the events are triggered, as logs mentioned the appropriate behaviours/messages
- although the logs mentions the replies, they do not show up in the public channel — it is completely OK if I DM the bot
