### ISSUE TITLE
How to set authentication hubot?

### ISSUE THREAD

**Issue by hoangnguyen1612** [hipchat/hubot-hipchat#229]
Hello world,

I have a problem. I have two hubots: "devbot" and "adminbot". They connected to hipchat successfully, I deployed them to heroku. "adminbot" is host of room and "devbot" is member.

Now, I want to set role for this hubots, I used "hubot-auth"  and then I run hubot, I got a error message: 
WARNING The HUBOT_AUTH_ADMIN environment variable not set

I also typed: heroku config and this is result:

HEROKU_URL:                 http://renewdevbot.herokuapp.com
HUBOT_ADAPTER_NAME:         hipchat
HUBOT_ADAPTER_USER:         273946_herokuhubot 
HUBOT_AUTH_ADMIN:           273946_1746790@chat.hipchat.com
HUBOT_HEROKU_KEEPALIVE_URL: https://renewdevbot.herokuapp.com/
HUBOT_HIPCHAT_JID:          273946_1746790@chat.hipchat.com
HUBOT_HIPCHAT_PASSWORD:     *********
HUBOT_HIPCHAT_ROOMS:        273946_herokuhubot
HUBOT_XMPP_ROOMS:           273946_herokuhubot

HUBOT_AUTH_ADMIN is set, but still show warning?

And in Hubot, I typed:

Hubot> hubot who has admin role

And this is result:
Shell: Sorry, only admins can assign roles.
Hubot> Shell: There are no people that have the 'admin' role.

Please help me, thank you so much!

**Comment by tjrivera** [comment]
Try setting HUBOT_AUTH_ADMIN to "1746790"

**Comment by rbergman** [comment]
Feel free to re-open if the proposed fix did not solve your issue.

**Comment by sravan-bala** [comment]
I  am using hipchat as a hubot adapter. How can I set roles on hipchat UI? Thanks!
