### ISSUE TITLE
Deploying to heroku fails with Failed at the node-expat@2.1.4 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by Sennevds** [hipchat/hubot-hipchat#232]
Hi,

I've searched here but can't find a solution. i'm trying to install hubot on heroku but when i try to deploy it to heroku i'm getting alot of errors.
i've uploaded the build log to paste bin:
http://pastebin.com/y3guQSyF
Everything works fine until i try to deploy it

**Comment by brennebeck** [comment]
@Sennevds I had to use the legacy buildpack to get this working. You can try:

```bash
heroku config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs#v63
```

I also set node to use v0.10.x.

**Comment by Sennevds** [comment]
Thanks setting the version of node did the trick.
