### ISSUE TITLE
Hubot connecting and responding, but doesn't show as logged in

### ISSUE THREAD

**Issue by ellisju** [hipchat/hubot-hipchat#233]
So at some point our robot stopped showing as logged in.  It responds to messages and works fine in pretty much every respect, but the OS X HipChat client shows it as offline, whereas the web client shows it as online and available.

Im wondering if this is some kind of HipChat client issue or maybe the Hubot module needs to be updated to account for some change in the API?

**Comment by esigler** [comment]
See https://github.com/hipchat/hubot-hipchat/issues/220 for details.
