### ISSUE TITLE
HUBOT_HIPCHAT_ROOMS_BLACKLIST not working

### ISSUE THREAD

**Issue by prassh123** [hipchat/hubot-hipchat#235]
I am starting the process by setting the env variable HUBOT_HIPCHAT_ROOMS_BLACKLIST, but that doesn't seem to stop the bot from joining the blacklisted room when invited. Is this a known issue?

**Comment by prassh123** [comment]
More info:

The first time it starts up, the jid is a string
    jid  12345_xxxxx@conf.hipchat.com
    blacklisted  [ 12345_xxxxx@conf.hipchat.com' ]

When someone invites or tags the bot from a blacklisted room, the jid received is an object
    
    jid  { local: '12345_xxxxx',
      domain: 'conf.hipchat.com',
      resource: null,
      user: '12345_xxxxx' }

    blacklisted   [ '25234_optimus_test@conf.hipchat.com' ]

As a result, it fails the below check in hipchat.coffee

    if jid in blacklisted_room_jids
          @logger.info "Not joining #{jid} because it is blacklisted"
          return

Let me know if I am incorrect

**Comment by rbergman** [comment]
Try PR #241.  If it works for you, I'll merge and publish.

**Comment by prassh123** [comment]
Thanks Robert. I will try this today and let you know.

**Comment by prassh123** [comment]
Yep. This works. I tested it.

**Comment by rbergman** [comment]
Merged.
