### ISSUE TITLE
Hubot fails to connect on hipchat

### ISSUE THREAD

**Issue by samgranieri** [hipchat/hubot-hipchat#239]
I'm trying a brand new install of hipchat running nodejs v0.12.2 on OSX Yosemite in homebrew. 
I'm getting a ton of HipChat connection errors
Here's a gist of everything https://gist.github.com/samgranieri/811a0fded03c3209129d

Am I doing anything wrong?

**Comment by cycomachead** [comment]
Are we supposed to use the hipchat adapter in the shell? I just tried it that way and got the same errors, I guess I've just always been running the shell adapter locally.

**Comment by cycomachead** [comment]
Update, so for me -- it was an enviornment variable issue like, #240 suggests fixing. However, I just tried with a bad JID / password combo and got the same error. With a good password all was well, at least for me. 

Obviously, I don't know what your password was, but you might try changing the export line to 
`export HUBOT_HIPCHAT_PASSWORD='password'` (note the quotes), incase there are any special characters.

**Comment by rbergman** [comment]
Thanks for the suggestion @cycomachead.  Does that help, @samgranieri?  Feel free to re-open this if it doesn't help.

**Comment by MrMMorris** [comment]
@cycomachead I just want you to know that you inadvertently made me realize I was using `HUBOT_HIPCHAT_PASS` instead of `HUBOT_HIPCHAT_PASSWORD`. Thanks for that. :+1:

**Comment by cycomachead** [comment]
No problem! :+1:
