### ISSUE TITLE
hipchat adapter is too coupled with heroku

### ISSUE THREAD

**Issue by hsingh23** [hipchat/hubot-hipchat#254]
Suppose I want hubot to work with my existing digital ocean - I don't need a lot of the heroku specific stuff. In fact with heroku's new every free app must sleep 6 hours, deploying to heroku becomes more trouble than it is worth.

**Comment by TheBrockEllis** [comment]
I agree that I would rather have alternate instructions on how to install it to my own server so I am not dependent on another 3rd party. Any one have any tips for installing Hubot on a local machine instead of Heroku?

**Comment by webhamm** [comment]
You can install easily on mac with yo. There aren't really any permission issues to worry about like on linux. The only Heroku specific item I have seen is a keepalive script that you can easily uninstall with npm **npm uninstall hubot-heroku-keepalive --save**
