### ISSUE TITLE
INFO Connection went offline - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by chriscareycode** [hipchat/hubot-hipchat#255]
Following the hubot setup instructions, setting up a new bot with the hipchat adapter. I'm using existing credentials from my old bot. When trying to connect, get the following :

---

$ ./start.sh 
[Wed Sep 23 2015 18:47:00 GMT-0400 (EDT)] INFO Connecting HipChat adapter...
createCredentials() is deprecated, use tls.createSecureContext instead
[Wed Sep 23 2015 18:47:01 GMT-0400 (EDT)] INFO Connection went offline
[Wed Sep 23 2015 18:47:01 GMT-0400 (EDT)] INFO Connection went offline
[Wed Sep 23 2015 18:47:01 GMT-0400 (EDT)] INFO Connection went offline
[Wed Sep 23 2015 18:47:01 GMT-0400 (EDT)] INFO Connection went offline
**\* a few hundred of these messages ***
[Wed Sep 23 2015 18:47:01 GMT-0400 (EDT)] INFO Connection went offline
[Wed Sep 23 2015 18:47:01 GMT-0400 (EDT)] INFO Connection went offline
[Wed Sep 23 2015 18:47:01 GMT-0400 (EDT)] INFO Connection went offline
[Wed Sep 23 2015 18:47:01 GMT-0400 (EDT)] INFO Connection went offline

(null):0
(null)

RangeError: Maximum call stack size exceeded

---

I'm running these versions:

"dependencies": {
    "feedparser": "^1.1.3",
    "hubot": "^2.16.0",
    "hubot-diagnostics": "0.0.1",
    "hubot-help": "^0.1.1",
    "hubot-hipchat": "^2.12.0-5",
    "hubot-redis-brain": "0.0.3",
    "hubot-scripts": "^2.16.2"
  },
  "engines": {
    "node": "0.12.0"
  }

**Comment by SteveEasley** [comment]
Check your HUBOT_HIPCHAT_PASSWORD. I had the same issue and narrowed it down to a password issue after downloading a jabber client and attempting to sign in with it.

**Comment by chriscareycode** [comment]
Boy do I feel dumb. Someone had erased my account! Thank you Steve!

**Comment by DavidR91** [comment]
Although that might solve @chriscareycode 's particular instance of this error, I suspect there may be a bigger problem here.

I'm actually seeing this issue pretty much daily on my hubot server. The connection drops and enters this maximum callstack issue every 4-5 hours (note the timestamps), despite having been persistently connected and working prior to it dropping:

```[Tue Sep 29 2015 13:47:26 GMT+0000 (UTC)] INFO Joining 282445_XX@conf.hipchat.com```

```[Tue Sep 29 2015 18:48:08 GMT+0000 (UTC)] INFO Connection went offline```

```[Tue Sep 29 2015 18:48:08 GMT+0000 (UTC)] ERROR RangeError: Maximum call stack size exceeded
  at emitNone (events.js:67:13)
  at Client.emit (events.js:166:7)
  at Client.<anonymous> (/hubot_root/node_modules/hubot-hipchat/node_modules/node-xmpp-client/index.js:185:22)
  at emitNone (events.js:72:20)
  at Connection.emit (events.js:166:7)
  at emitter.end.emitter.disconnect (/hubot_root/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/reconnect-core/index.js:108:15)
  at Connection.end.disconnect (/hubot_root/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:124:9)
  at Client.Session.end (/hubot_root/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/session.js:191:25)
  at Connector.module.exports.Connector.disconnect (/hubot_root/node_modules/hubot-hipchat/src/connector.coffee:105:5, <js>:88:19)
  at Connector.disconnect (/hubot_root/node_modules/hubot-hipchat/src/connector.coffee:23:1, <js>:3:61)
  at Connector.onOffline (/hubot_root/node_modules/hubot-hipchat/src/connector.coffee:506:3, <js>:460:17)
  at emitNone (events.js:67:13)```

I'm reasonably sure my network is stable enough for it to not drop due to connection reset etc.

Does Hipchat operate any kind of idle timeout?

And regardless, is it possible to change this behaviour so that when a connection *does* go offline, it can reconnect more gracefully? 

(In fact actually, in the event of this error, I would much prefer it if hubot straight up terminated - at least then forver of docker could just restart it)

Thoughts / opinions on stuff I can check?

**Comment by Snorlock** [comment]
Im also recieving this every other week not sure to why its happening
First line its still working, then suddenly BÆM, this loops.

[Mon Oct 05 2015 08:33:10 GMT+0200 (CEST)] DEBUG  OUT > <r/>
[Mon Oct 05 2015 08:33:33 GMT+0200 (CEST)] DEBUG Disconnecting here
[Mon Oct 05 2015 08:33:33 GMT+0200 (CEST)] INFO Connection went offline
[Mon Oct 05 2015 08:33:33 GMT+0200 (CEST)] DEBUG Disconnecting here
[Mon Oct 05 2015 08:33:33 GMT+0200 (CEST)] INFO Connection went offline

(null):0
(null)

RangeError: Maximum call stack size exceeded

What might the reason be?
A simple restart fixes the issue.

**Comment by Snorlock** [comment]
More info on this issue. If I type the wrong password, and it tries to connect, it ends up in this call stack loop. So its easy to force it, as mentioned earlier in this issue.

I believe it might be when he looses connection and cannot connect for some reason. That might be network problems or other problems. Then he ends up in this loop, and bam! Maximum callstack loop.

Any thoughts?

**Comment by chlunde** [comment]
This looks like the same issue as #257.

**Comment by aaronblythe** [comment]
I submitted pull request #267 

I believe that there is a circular call between disconnect and the offline event.

https://github.com/node-xmpp/node-xmpp-client/blob/8bb758d181da25a60bde7932c90b1cca7a0dc793/lib/Client.js#L158

Thus creating:
disconnect --> offline --> disconnect --> offline --> disconnect --> ... ∞

Which manifests in the logs like this:

    [Tue Dec 22 2015 22:06:22 GMT+0000 (UTC)] DEBUG  OUT > <r/>
    [Tue Dec 22 2015 22:06:29 GMT+0000 (UTC)] INFO Connection went offline
    [Tue Dec 22 2015 22:06:29 GMT+0000 (UTC)] DEBUG Disconnecting here
    [Tue Dec 22 2015 22:06:29 GMT+0000 (UTC)] INFO Connection went offline
    [Tue Dec 22 2015 22:06:29 GMT+0000 (UTC)] DEBUG Disconnecting here
    [Tue Dec 22 2015 22:06:29 GMT+0000 (UTC)] INFO Connection went offline
    [Tue Dec 22 2015 22:06:29 GMT+0000 (UTC)] DEBUG Disconnecting here
    [Tue Dec 22 2015 22:06:29 GMT+0000 (UTC)] INFO Connection went offline
    ...
    [Tue Dec 22 2015 22:06:30 GMT+0000 (UTC)] ERROR RangeError: Maximum call stack size exceeded

ultimately ending in a StackOverflow.

I was able to recreate this issue by running the bot in docker locally and connecting to hip chat through configuration.  Once successfully completing a hubot ping-pong, i disconnected from the internet.  I was able to recreate every time until I removed the circular call.

When I remove the circular call, I then get these logs:

    [Tue Dec 22 2015 23:24:00 GMT+0000 (UTC)] DEBUG  OUT > <r/>
    [Tue Dec 22 2015 23:24:30 GMT+0000 (UTC)] DEBUG  OUT > <r/>
    [Tue Dec 22 2015 23:24:43 GMT+0000 (UTC)] INFO Connection went offline
    [Tue Dec 22 2015 23:24:43 GMT+0000 (UTC)] INFO Connection was closed
    [Tue Dec 22 2015 23:24:43 GMT+0000 (UTC)] DEBUG Disconnecting here
    [Tue Dec 22 2015 23:24:43 GMT+0000 (UTC)] INFO Connection went offline
    [Tue Dec 22 2015 23:24:43 GMT+0000 (UTC)] INFO Disconnected from hipchat.com
    [Tue Dec 22 2015 23:24:43 GMT+0000 (UTC)] INFO Waiting 8s and then retrying...
    [Tue Dec 22 2015 23:24:51 GMT+0000 (UTC)] INFO Attempting to reconnect...

Then connection resumes correctly and I can interact with the bot when plugging back in.

**Comment by rberrelleza** [comment]
Closing since #304 has been merged now.
