### ISSUE TITLE
Not hearing commands

### ISSUE THREAD

**Issue by bporter2387** [hipchat/hubot-hipchat#266]
I was able to get Hubot-Slack to work and I was able to send commands via curl with the API v2 and v1. I've tried NodeJS versions .10 that ships with CentOS 7, NodeJS .12.2, and 4.2.3. None of them work with hubot hipchat even though it says it's connected. I've tried naming the bot 'hubot' as well as my hipchat username 'BrettPorter' - neither worked. 

I've also tried CentOS 6 with no luck. Is there a better way to debug this?

export HUBOT_HIPCHAT_TOKEN="**************************"
export HUBOT_HIPCHAT_JID="******************@chat.hipchat.com"
export HUBOT_HIPCHAT_PASSWORD="**********"
export HUBOT_LOG_LEVEL=debug
bin/hubot --adapter hipchat

[Thu Dec 10 2015 17:30:58 GMT-0500 (EST)] DEBUG Loading adapter hipchat
[Thu Dec 10 2015 17:30:59 GMT-0500 (EST)] DEBUG HipChat adapter options: {"jid":"************@chat.hipchat.com","password":"************","token":"*******************","rooms":"All","rooms_blacklist":"","rooms_join_public":true,"host":null,"bosh":{"url":null},"autojoin":true,"xmppDomain":null,"reconnect":true}
[Thu Dec 10 2015 17:30:59 GMT-0500 (EST)] INFO Connecting HipChat adapter...
createCredentials() is deprecated, use tls.createSecureContext instead
[Thu Dec 10 2015 17:30:59 GMT-0500 (EST)] DEBUG  OUT > <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">NDA1NjQzXzI0ODg3MzNAY2hhdC5oaXBjaGF0LmNvbQA0MDU2NDNfMjQ4ODczMwBCUix3ZHk5Mj8h</auth>
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG  OUT > <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>hubot-hipchat</resource></bind>
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG  OUT > <session xmlns="urn:ietf:params:xml:ns:xmpp-session"/>
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG  OUT > <presence type="available"><show>chat</show><c xmlns="http://jabber.org/protocol/caps" node="http://hipchat.com/client/bot" ver="hubot-hipchat:2.12.0-6"/></presence>
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG  OUT > <iq type="get" id="1"><vCard xmlns="vcard-temp"/></iq>
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] INFO Connected to hipchat.com as @BrettPorter
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Loading scripts from /home/hubot/hubot/scripts
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/scripts/example.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Loading scripts from /home/hubot/hubot/src/scripts
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Loading hubot-scripts from /home/hubot/hubot/node_modules/hubot-scripts/src/scripts
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Sending connected event
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG  OUT > <iq type="get" id="2"><query xmlns="jabber:iq:roster"/></iq>
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Loading external-scripts from npm packages
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-diagnostics/src/diagnostics.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-help/src/help.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-heroku-keepalive/src/heroku-keepalive.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-google-images/src/google-images.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-google-translate/src/google-translate.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-pugme/src/pugme.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-maps/src/maps.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-redis-brain/src/redis-brain.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-rules/src/rules.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG  OUT > <iq to="conf.hipchat.com" type="get" id="3"><query xmlns="http://jabber.org/protocol/disco#items"/></iq>
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-shipit/src/shipit.coffee
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] DEBUG hubot-redis-brain: Successfully connected to Redis
[Thu Dec 10 2015 17:31:00 GMT-0500 (EST)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] INFO Joining 405643_worldboxme@conf.hipchat.com
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] DEBUG  OUT > <presence to="405643_worldboxme@conf.hipchat.com/Brett Porter"><x xmlns="http://jabber.org/protocol/muc"/><history xmlns="http://jabber.org/protocol/muc" maxstanzas="0"/></presence>
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] INFO Joining 405643_scp@conf.hipchat.com
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] DEBUG  OUT > <presence to="405643_scp@conf.hipchat.com/Brett Porter"><x xmlns="http://jabber.org/protocol/muc"/><history xmlns="http://jabber.org/protocol/muc" maxstanzas="0"/></presence>
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] DEBUG No listeners executed; falling back to catch-all
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] DEBUG No listeners executed; falling back to catch-all
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] DEBUG No listeners executed; falling back to catch-all
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] DEBUG No listeners executed; falling back to catch-all
[Thu Dec 10 2015 17:31:01 GMT-0500 (EST)] DEBUG No listeners executed; falling back to catch-all
[Thu Dec 10 2015 17:31:30 GMT-0500 (EST)] DEBUG  OUT > <r/>
[Thu Dec 10 2015 17:32:00 GMT-0500 (EST)] DEBUG  OUT > <r/>
[Thu Dec 10 2015 17:32:30 GMT-0500 (EST)] DEBUG  OUT > <r/>

**Comment by shubhamitc** [comment]
Did you find the solution as i am still struggling.

**Comment by luciomr** [comment]
According to your log (thank you for it by the way), you didn't set the xmppDomain. It's value is null:

`"xmppDomain":null,`

Now, if by commands you mean getting the bot to listen to @mentions to its user, you need to set its value. Otherwise, the bot will only reply to commands in chats 1-to-1. 

[According to the documentation](https://github.com/hipchat/hubot-hipchat), you should define the value of an environment variable called HUBOT_HIPCHAT_XMPP_DOMAIN. The value that worked for me (and was included also in the docs) is **"btf.hipchat.com"**

I got the answer to that the hard way (because I skipped the heroku part of the documentation): by looking at the code.
