### ISSUE TITLE
Utilize official Hipchat API

### ISSUE THREAD

**Issue by RichiCoder1** [hipchat/hubot-hipchat#271]
Would be great to switch for using XMPP to Hipchat's v2 API, especially since that seems to be the sactioned path forward for other integrations (and allows access tokens instead of user&pass).

https://www.hipchat.com/docs/apiv2

**Comment by SamWhited** [comment]
Note that you can login with a valid access token over XMPP too by using the `X-OAUTH` or `X-HIPCHAT-OAUTH2` SASL mechanisms. These could be supported as well to fix these problems if they're not already.

**Comment by cycomachead** [comment]
There is a bit of work in #270 which uses the API for specific functions, but not as a complete replacement...

**Comment by rbergman** [comment]
The v2 API is not a 100% replacement for the capabilities of XMPP, though you are right -- it _is_ the way forward for HipChat integrations and "bots".  Quite a bit of support exists for creating v2 integrations, but porting hubot-hipchat to the v2 API is probably more work than just implementing new-addons with one of the node.js or other SDKs HipChat already supports for that purpose.
