### ISSUE TITLE
User information stored in brain twice

### ISSUE THREAD

**Issue by seanfitzgeraldsc** [hipchat/hubot-hipchat#286]
This ended up being the root cause of what looks like a bunch of similar issues to #80 , when digging through the contents of brain and adding a bunch of logging to getUserForName, I discovered that hipchat assigns different identifiers for users in each room, as well as in 1:1 chat. The user as identified in a room roster has mention information, whereas the 1:1 does not. I'm still trying to see if this is part of the hipchat xmpp protocol or part of the hubot-hipchat adapter. 

Brain.getUserForName does not break out of its loop when it finds the first user, so as the count of user objects grows over time, the behavior does not remain consistent for any given user.

```
"2503896": {
            "email_address": "sean.fitzgerald@******.com",
            "id": "2503896",
            "jid": "*****_2503896@chat.hipchat.com",
            "mention_name": "seanfitz",
            "name": "Sean Fitzgerald",
            "room": "*****_bottest@conf.hipchat.com"
        }
"4694198": {
            "id": "4694198",
            "name": "Sean Fitzgerald",
            "room": "******_private_room@conf.hipchat.com"
        }
```

**Comment by seanfitzgeraldsc** [comment]
I've pushed #287 as a proposed patch.

**Comment by seanfitzgeraldsc** [comment]
Hey @hipchat, is this repo still monitored?

**Comment by rberrelleza** [comment]
#303 fixed this issue
