### ISSUE TITLE
Exceeding message size limit fails silently

### ISSUE THREAD

**Issue by njam** [hipchat/hubot-hipchat#289]
When sending a message with a size of approximately 40kb or greater the message is not delivered.
There's not error about that from hubot-hipchat.

Reproduce with this:
```js
module.exports = function(robot) {
  return robot.catchAll(function(chat) {
    chat.send('x'.repeat(40000));
  });
};
```

Do we receive something back from the server from which we can identify this case?
Or should we detect it in hubot-hipchat?

**Comment by yixiaol-m** [comment]
+1 for the issue. Although not sure if this is an issue originated from the hipchat api or the hubot integration.

**Comment by njam** [comment]
too old
