### ISSUE TITLE
How do you send private message?

### ISSUE THREAD

**Issue by doapp-ryanp** [hipchat/hubot-hipchat#29]
I'm trying to send a private message to the user that sent a command to my bot.  I've looked over https://github.com/hipchat/hubot-hipchat/issues/16 but still cant get it to work.  Here is my code:

```
module.exports = (robot) ->
  robot.respond /deploy (.+) (prod|staging|test) (.+)/i, (msg) ->
  #below works to send an @user message
  robot.send msg.message.user, 'test send'
  #does not work - robot.reply msg.message.user, 'test pm'
  #below does not work either, get ERROR Unable to call the listener: TypeError: Object #<Robot> has no method 'message'
  robot.message msg.message.user.jid, 'test pm'
```

what am I doing wrong? or is this feature not supported.

**Comment by jonyeezs** [comment]
I've tested this on hipchat doesn't work.

hipchat relies on the jabba id aka jid.

@ibash  is spot on. That's what we'll need `msg.message?.user?.jid`

I've done a quick test and that worked for hipchat.
