### ISSUE TITLE
Will this adapter work with Stride?

### ISSUE THREAD

**Issue by ndrake** [hipchat/hubot-hipchat#301]
Will this adapter work with Stride?

**Comment by cycomachead** [comment]
Sigh, none of the docs mention XMPP or API so that's concerning, though the app platform apps seem to be supported, but I don't know if there's a Hubot in their app platform?

**Comment by rberrelleza** [comment]
No, Stride doesn't have support for XMPP. 

We just released the Stride API, I do recommend you take a look to it: https://developer.atlassian.com/cloud/stride/integrating-with-stride/. Maybe you can build an integration for your use cases with it?
