### ISSUE TITLE
Can Hubot join all private rooms without being invited?

### ISSUE THREAD

**Issue by aysong** [hipchat/hubot-hipchat#302]
Haven't seen any issues or any matter on the topic. Is it possible to have Hubot join ALL rooms (including private)? The HUBOT_HIPCHAT_ROOMS env variable is set to "All" but it only seems to encompass any public rooms. I would like for Hubot to join any and all private rooms without setting it manually.

**Comment by rberrelleza** [comment]
It's not possible. Only a member of a private room can join a private room. (from privacy perspective, hubot must follow the same rules as a normal hipchat user)
