### ISSUE TITLE
HuBot won't join a private room

### ISSUE THREAD

**Issue by johnnagro** [hipchat/hubot-hipchat#6]
We're running hubot on heroku created via the https://hubot-factory.herokuapp.com/ yesterday. We have the bot in a public room and everything is fine and cool but today we tried to invite the bot to a private room and nothing happened. We've restarted the bot a number of times and it doesn't appear to resolve the issue.

Currently the bot is online and listening in the public room, but marked offline and not listening in the private room. Also, in the one-on-one chat the bot is always marked offline, even though it will respond.

thanks!

Here is a related issue i found but the resolution doesn't work: https://github.com/github/hubot/issues/78

**Comment by sreenath886** [comment]
I have a hubot configured in heroku and it trying to connects to our cloude Hipchat server, but my hubot is not visible in my hipchat room and its not responding.i checked the heroku logs. its telling "hubot is joining the room" , but nothing in the room.
But i can see bot in my chat session:https://<hipchat web account url>/account/sessions 
My heroku config:
heroku config:add HUBOT_ADAPTER_NAME=hipchat 
heroku config:add HUBOT_ADAPTER_USER=<room name> 
heroku config:add HUBOT_HIPCHAT_JID=<my-jid of new hipchat account>@chat.hipchat.com> 
heroku config:add HUBOT_HIPCHAT_PASSWORD="password" 
heroku config:add HUBOT_HIPCHAT_ROOMS=All

Is this Config Vars are correct and anything more i need to add?
Do you have any idea how to invite the Bot in Hipchat room?

**Comment by alessandro-aglietti** [comment]
export HUBOT_HIPCHAT_JID=xxxx@chat.hipchat.com
export HUBOT_HIPCHAT_PASSWORD=xxxxxxx
export HUBOT_HIPCHAT_JOIN_PUBLIC_ROOMS=false
export HUBOT_HIPCHAT_ROOMS=xxx@conf.hipchat.com

with this vars all working fine: when I mention with @ the bot it join the
room.

hope this help

**Comment by sreenath886** [comment]
Hi,
Thanks for the replay.Bot is active in chat session.i can see my boat in below url 
https://www.hipchat.com/account/sessions

But its not joining in any rooms [both private and public].I Set the HUBOT_HIPCHAT_ROOMS=xxx@conf.hipchat.com what you mentioned above.

Any idea about this issue?
Am i want to invite to bot to join in my rooms and any idea how to invite the Bot in Hipchat room?


--Sreenath
